import { LotrCardDef, LotrSkill, LotrCardColor, LotrRace, LotrRegion, LotrManeuverType } from "@/types/lotr";

type CD = LotrCardDef;

function c(id: string, name: string, ch: number, color: LotrCardColor,
          coinCost: number, skillCost: LotrSkill[], chainCost: string | null,
          chain: string | null, extra: Partial<CD> = {}): CD {
  return { id, name, chapter: ch, color, coinCost, skillCost, chainCost, chainingSymbol: chain, ...extra };
}

export const ALL_CARDS: LotrCardDef[] = [
  c("C1-01","Orcs",1,"RED",0,["RUSE"],null,"Bow",{redBannerRegions:["GONDOR","ROHAN"],redUnitCount:1}),
  c("C1-02","Fellowship",1,"RED",0,[],null,"Helmet",{redBannerRegions:["ENEDWAITH","RHOVANION"],redUnitCount:1}),
  c("C1-03","Balrog",1,"RED",0,[],null,"Sword",{redBannerRegions:["LINDON","ARNOR"],redUnitCount:1}),
  c("C1-04","Gimli",1,"GREEN",0,["LEADERSHIP"],null,"Anvil",{greenRace:"DWARVES"}),
  c("C1-05","Legolas",1,"GREEN",0,["KNOWLEDGE"],null,"Harp",{greenRace:"ELVES"}),
  c("C1-06","Aragorn",1,"GREEN",0,["KNOWLEDGE"],null,"Horseshoe",{greenRace:"HUMANS"}),
  c("C1-07","Frodo & Sam",1,"GREEN",0,["LEADERSHIP"],null,"Pot",{greenRace:"HOBBITS"}),
  c("C1-08","Gollum - Cave 1",1,"BLUE",0,[],null,null,{blueRings:1}),
  c("C1-09","Gollum - Cave 2",1,"BLUE",1,[],null,"Fish",{blueRings:1}),
  c("C1-10","Gollum - Cave 3",1,"BLUE",0,["STRENGTH"],null,"Horse",{blueRings:1}),
  c("C1-11","Gollum - Cave 4",1,"BLUE",0,["COURAGE"],null,"Backpack",{blueRings:1}),
  c("C1-12","Dead Marshes 1",1,"GREY",0,[],null,null,{greySkills:[["COURAGE"]]}),
  c("C1-13","Dead Marshes 2",1,"GREY",0,[],null,null,{greySkills:[["COURAGE"]]}),
  c("C1-14","Dwarf Smith 1",1,"GREY",0,[],null,null,{greySkills:[["STRENGTH"]]}),
  c("C1-15","Dwarf Smith 2",1,"GREY",0,[],null,null,{greySkills:[["STRENGTH"]]}),
  c("C1-16","Archives - Minas Tirith 1",1,"GREY",0,[],null,null,{greySkills:[["KNOWLEDGE"]]}),
  c("C1-17","Imrahil - Captain of the West 1",1,"GREY",0,[],null,null,{greySkills:[["LEADERSHIP"]]}),
  c("C1-18","Nazgul 1",1,"GREY",0,[],null,null,{greySkills:[["RUSE"]]}),
  c("C1-19","Nazgul 2",1,"GREY",0,[],null,null,{greySkills:[["RUSE"]]}),
  c("C1-20","Gold Coins 1",1,"YELLOW",0,[],null,null,{yellowCoins:2}),
  c("C1-21","Gold Coins 2",1,"YELLOW",0,[],null,null,{yellowCoins:2}),
  c("C1-22","Gold Coins 3",1,"YELLOW",0,[],null,null,{yellowCoins:2}),
  c("C1-23","Gold Coins 4",1,"YELLOW",0,[],null,null,{yellowCoins:2}),

  c("C2-01","Uruk-hai",2,"RED",0,["RUSE","RUSE","RUSE"],"Bow",null,{redBannerRegions:["GONDOR","MORDOR"],redUnitCount:2}),
  c("C2-02","Spearmen",2,"RED",0,["STRENGTH","STRENGTH","COURAGE"],"Helmet","Armor",{redBannerRegions:["LINDON","ENEDWAITH"],redUnitCount:2}),
  c("C2-03","Archers",2,"RED",0,["RUSE","RUSE","KNOWLEDGE"],"Sword","Waraxe",{redBannerRegions:["MORDOR","ROHAN"],redUnitCount:2}),
  c("C2-04","First Light of the Fifth Day",2,"RED",0,["COURAGE","COURAGE","LEADERSHIP"],null,null,{redBannerRegions:["ARNOR","RHOVANION"],redUnitCount:2}),
  c("C2-05","Attack Troll",2,"RED",0,["RUSE","STRENGTH","COURAGE"],null,null,{redBannerRegions:["LINDON","ROHAN"],redUnitCount:2}),
  c("C2-06","Dwarves",2,"GREEN",0,["STRENGTH","STRENGTH","LEADERSHIP"],"Anvil",null,{greenRace:"DWARVES"}),
  c("C2-07","Galadriel",2,"GREEN",0,["COURAGE","LEADERSHIP","KNOWLEDGE"],"Harp",null,{greenRace:"ELVES"}),
  c("C2-08","Eowyn",2,"GREEN",0,["COURAGE","COURAGE","KNOWLEDGE"],"Horseshoe","Scroll",{greenRace:"HUMANS"}),
  c("C2-09","Merry & Pippin",2,"GREEN",0,["RUSE","RUSE","LEADERSHIP"],"Pot","Chestnut",{greenRace:"HOBBITS"}),
  c("C2-10","Gollum - River 1",2,"BLUE",0,["COURAGE","STRENGTH"],"Horse",null,{blueRings:1}),
  c("C2-11","Gollum - River 2",2,"BLUE",1,[],"Backpack",null,{blueRings:1}),
  c("C2-12","Gollum - River 3",2,"BLUE",0,["STRENGTH","COURAGE","COURAGE"],null,"Campfire",{blueRings:2}),
  c("C2-13","Gollum - River 4",2,"BLUE",0,["STRENGTH","STRENGTH","KNOWLEDGE"],null,"Bedroll",{blueRings:2}),
  c("C2-14","Gollum - River 5",2,"BLUE",0,["RUSE","STRENGTH"],null,null,{blueRings:1}),
  c("C2-15","Archives - Minas Tirith 2",2,"GREY",0,[],null,null,{greySkills:[["KNOWLEDGE"]]}),
  c("C2-16","Imrahil - Captain of the West 2",2,"GREY",0,[],null,null,{greySkills:[["LEADERSHIP"]]}),
  c("C2-17","Spiders of Mirkwood",2,"GREY",1,[],null,null,{greySkills:[["COURAGE","COURAGE"]]}),
  c("C2-18","Oliphanut",2,"GREY",1,[],null,null,{greySkills:[["STRENGTH","STRENGTH"]]}),
  c("C2-19","Lothlorien Cloak",2,"GREY",1,[],null,null,{greySkills:[["RUSE","RUSE"]]}),
  c("C2-20","Captains of the West",2,"GREY",1,["RUSE"],null,null,{greySkills:[["LEADERSHIP"],["KNOWLEDGE"]]}),
  c("C2-21","Ambush",2,"GREY",1,["LEADERSHIP","KNOWLEDGE"],null,null,{greySkills:[["RUSE"],["STRENGTH"],["COURAGE"]]}),
  c("C2-22","Bags of Gold",2,"YELLOW",0,[],null,"Chest",{yellowCoins:3}),
  c("C2-23","Treasure Chests 1",2,"YELLOW",0,[],null,null,{yellowCoins:4}),

  c("C3-01","Minas Tirith",3,"RED",0,["STRENGTH","STRENGTH","COURAGE","COURAGE"],"Armor",null,{redBannerRegions:["ENEDWAITH","ROHAN"],redUnitCount:3}),
  c("C3-02","Banners",3,"RED",0,["RUSE","STRENGTH","LEADERSHIP","LEADERSHIP","KNOWLEDGE"],"Waraxe",null,{redBannerRegions:["GONDOR","ARNOR"],redUnitCount:3}),
  c("C3-03","Oliphanuts",3,"RED",0,["RUSE","RUSE","COURAGE","COURAGE"],null,null,{redBannerRegions:["ENEDWAITH","ARNOR"],redUnitCount:3}),
  c("C3-04","Nazgul-Bird",3,"RED",0,["RUSE","RUSE","RUSE","LEADERSHIP","LEADERSHIP"],null,null,{redBannerRegions:["RHOVANION","GONDOR"],redUnitCount:3}),
  c("C3-05","Mountain Trolls",3,"RED",0,["RUSE","RUSE","COURAGE","KNOWLEDGE","KNOWLEDGE"],null,null,{redBannerRegions:["LINDON","MORDOR"],redUnitCount:3}),
  c("C3-06","Imrahil's Cavalry",3,"RED",0,["RUSE","STRENGTH","STRENGTH","COURAGE","COURAGE"],null,null,{redBannerRegions:["RHOVANION","MORDOR"],redUnitCount:3}),
  c("C3-07","Saruman",3,"GREEN",0,["STRENGTH","LEADERSHIP","KNOWLEDGE"],null,null,{greenRace:"WIZARDS"}),
  c("C3-08","Gandalf",3,"GREEN",0,["RUSE","RUSE","LEADERSHIP","LEADERSHIP"],"Scroll",null,{greenRace:"WIZARDS"}),
  c("C3-09","Treebeard",3,"GREEN",0,["STRENGTH","STRENGTH","KNOWLEDGE","KNOWLEDGE"],"Chestnut",null,{greenRace:"ENTS"}),
  c("C3-10","Quickbeam",3,"GREEN",0,["COURAGE","COURAGE","LEADERSHIP","KNOWLEDGE"],null,null,{greenRace:"ENTS"}),
  c("C3-11","Gollum - Close 1",3,"BLUE",0,["RUSE","RUSE","COURAGE","COURAGE"],"Fish",null,{blueRings:2}),
  c("C3-12","Gollum - Close 2",3,"BLUE",0,["RUSE","RUSE","RUSE","STRENGTH","STRENGTH","STRENGTH"],"Campfire",null,{blueRings:2}),
  c("C3-13","Gollum - Close 3",3,"BLUE",0,["RUSE","RUSE","RUSE","COURAGE"],"Bedroll",null,{blueRings:2}),
  c("C3-14","Gollum - Close 4",3,"BLUE",0,["STRENGTH","LEADERSHIP"],null,null,{blueRings:2}),
  c("C3-15","Gollum - Close 5",3,"BLUE",3,[],null,null,{blueRings:3}),
  c("C3-16","Battering Ram",3,"PURPLE",0,["STRENGTH","STRENGTH","LEADERSHIP"],null,null,{purpleManeuvers:["REMOVE_ENEMY_UNIT","STEAL_COIN","MOVE_UNIT"] as LotrManeuverType[]}),
  c("C3-17","Orcs",3,"PURPLE",0,["RUSE","STRENGTH","COURAGE","KNOWLEDGE"],null,null,{purpleManeuvers:["STEAL_COIN","MOVE_UNIT","MOVE_UNIT"] as LotrManeuverType[]}),
  c("C3-18","Ballista",3,"PURPLE",0,["STRENGTH","COURAGE","KNOWLEDGE","KNOWLEDGE"],null,null,{purpleManeuvers:["REMOVE_ENEMY_UNIT","REMOVE_ENEMY_UNIT","STEAL_COIN"] as LotrManeuverType[]}),
  c("C3-19","Swords Orc",3,"PURPLE",0,["COURAGE","COURAGE","COURAGE","LEADERSHIP"],null,null,{purpleManeuvers:["REMOVE_ENEMY_UNIT","STEAL_COIN","STEAL_COIN"] as LotrManeuverType[]}),
  c("C3-20","Mountain Army",3,"PURPLE",0,["STRENGTH","STRENGTH","STRENGTH","KNOWLEDGE"],null,null,{purpleManeuvers:["REMOVE_ENEMY_UNIT","MOVE_UNIT","MOVE_UNIT"] as LotrManeuverType[]}),
  c("C3-21","Hill Army",3,"PURPLE",0,["COURAGE","COURAGE","LEADERSHIP","KNOWLEDGE"],null,null,{purpleManeuvers:["MOVE_UNIT","MOVE_UNIT","MOVE_UNIT"] as LotrManeuverType[]}),
  c("C3-22","Treasure Chests 2",3,"YELLOW",0,["RUSE","RUSE","COURAGE"],"Chest",null,{yellowCoins:5}),
  c("C3-23","Treasure Chests 3",3,"YELLOW",0,["RUSE","LEADERSHIP","KNOWLEDGE"],null,null,{yellowCoins:5}),
];

const cardMap = new Map(ALL_CARDS.map(c => [c.id, c]));
export function getCardDef(id: string): LotrCardDef | undefined { return cardMap.get(id); }
